language: java
before_install:
- chmod +x mvnw
env:
  global:
    secure: omKXRtU3koj55Bz/4UqUNVEOH4DDHe6B9culqDiat+5Ra0+ttnNzXFfr75llqXYTV71U89D1bWhhJGnpg+yCR56wVfMuJzfpIbTCF3I7YjIQY5XFw7901JaqPnjnldLwEc6Nv5DOCaea+1X9yvB0lmaSUPlrp5MJCToxGcyvt+PDTpqJQ6cQC67WKdmeQxFJxC+HC70WwEBLlxng9YZdDYlJeRu9ibNpBrf0vYSIiSQspwzdPN2laEW1OmMsZ3FmT1+gEQ4D/eOWQyyJYLXawKuSCO7QJ8JukHjaHZl+oKoErfuJP/wyw1s6KIorPWY7gNSQy8CXwbRLcX2nFzdbjdEfyC/MrZd8a2mEYESv+hzfZFBBGRaXmD0kq3pXBHQP1pxBYjQR9mFZuL38TIq30nU5yOXHGzJDXf3b4+Ios+BhaTWF0BzZ2Snz0z2N2SU171a4H8LtalRf/AxjuQypIieZuQqbne7SvjMTwmw8gSSpRTDcC/X0JxfkJFgfYUxXOj7kWQ2ZeFk5+0kiac+QJn3pKzQta5F+GCVCRWUfyu7judrwVqPfef7TqhT6auUj8u9tM605599bdwTLufK9zSOpAoK+6+8O9pA3xx+z/6wN2qWOA/luIRFKWIqYxN9luXdVqhNOwnbatKiEyRMQVn2UoSX+l8+b3dvIwMbhJk8=
